# -*- coding: utf-8 -*-
"""Telephone Directory.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mYQslAaLiWWeMA5NZVKejNn0WE7rUgCg

Install
"""

!pip install dnspython
!pip install pymongo[srv]



import pymongo
client = pymongo.MongoClient("mongodb+srv://archit:1234@cluster0.iodze.mongodb.net/telephone_db?retryWrites=true&w=majority")
db = client.student

records=db.phonebook
#defining the db name
#"records" is the object
client.list_database_names()


db=client.telephone_db
records=db.phonebook

mylist =[
         {"name":"Alex","phone number":"9678432100","address":"Chennai"},
         {"name":"Blaze","phone number":"9876543660","address":"Delhi"},
         {"name":"Cathy","phone number":"9876543210","address":"Mumbai"},
         {"name":"Danial","phone number":"9836544510","address":"Pune"},
         {"name":"Ethan","phone number":"9872943210","address":"Chandigarh"},
         {"name":"Felix","phone number":"9234543210","address":"Punjab"},
]
#inserting many(Create many) C
x=records.insert_many(mylist)

#insert one(Create one)
records.insert_one(
   {
      "name": "John","phone number":"9998132100","address":"hyderabad"
   }
)

#Finding all the records(Read)R
for x in records.find():
  print(x)

#Update one(Update)U
records.update_one({"name":"Ethan"}, {"$set":{"name":"Eminem"}})

#Deleting(Delete one)D
records.delete_one({"name":"John"})